name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REPO_BACKEND }}:latest ./backend
          docker push ${{ secrets.ECR_REPO_BACKEND }}:latest

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REPO_FRONTEND }}:latest ./frontend
          docker push ${{ secrets.ECR_REPO_FRONTEND }}:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Kubeconfig
        uses: aws-actions/eks-update-kubeconfig@v1
        with:
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          region: ${{ secrets.AWS_REGION }}

      - name: Deploy Backend to EKS
        run: |
          kubectl apply -f ./k8s/backend-deployment.yaml

      - name: Deploy Frontend to EKS
        run: |
          kubectl apply -f ./k8s/frontend-deployment.yaml
